<template>
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa debitis eius exercitationem iste possimus quis similique veniam vero. Aliquam autem ea eos ipsa itaque iusto labore libero magni quaerat quod!</p>
        <!--<tr>
            <td>{{ customer.name}} </td>
        </tr> -->
    </div>
</template>

<script>
    export default {
        props:["product"]
    }
</script>
